# Generated by Django 4.0.6 on 2022-07-08 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ebook',
            old_name='cvr_url',
            new_name='cover_url',
        ),
    ]
